In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import yfinance as yf
import pandas_datareader.data as web

**DOWNLOADING DATA FROM YFINANCE**

In [2]:
tickers = ['GS','MSCI','V','CRISIL.NS','HDFCBANK.NS']
data = yf.download(tickers=tickers,start='2019-01-01',end='2026-01-01')['Close']
data

/tmp/ipykernel_924/2009219871.py:2: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(tickers=tickers,start='2019-01-01',end='2026-01-01')['Close']
[*********************100%***********************]  5 of 5 completed

Ticker        CRISIL.NS          GS  HDFCBANK.NS        MSCI           V
Date
2019-01-01  1430.624268         NaN   496.185883         NaN         NaN
2019-01-02  1435.571655  144.753723   491.658569  135.801575  126.068092
2019-01-03  1447.055908  142.633270   487.800995  130.626099  121.525017
2019-01-04  1436.808350  147.294876   489.106018  135.487411  126.760445
2019-01-07  1448.645996  148.111084   489.845184  136.115845  129.046265
...                 ...         ...          ...         ...         ...
2025-12-24  4240.708008  902.036438   980.975220  577.381165  353.675964
2025-12-26  4209.180664  898.332275   975.958191  580.596802  353.536560
2025-12-29  4254.050781  883.614990   975.564697  581.361023  353.148132
2025-12-30  4141.974609  875.929443   974.777771  577.877380  352.162231
2025-12-31  4271.148926  870.561523   975.072876  569.421387  349.264221

[1816 rows x 5 columns]

**EXPLORATORY DATA ANALYSIS**

In [3]:
data.isnull().sum().sum()

np.int64(340)

In [4]:
data.dropna(inplace=True)

In [5]:
data.isnull().sum().sum()

np.int64(0)

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 1674 entries, 2019-01-02 to 2025-12-31
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   CRISIL.NS    1674 non-null   float64
 1   GS           1674 non-null   float64
 2   HDFCBANK.NS  1674 non-null   float64
 3   MSCI         1674 non-null   float64
 4   V            1674 non-null   float64
dtypes: float64(5)
memory usage: 78.5 KB

In [7]:
data.describe()

Ticker    CRISIL.NS           GS  HDFCBANK.NS         MSCI            V
count   1674.000000  1674.000000  1674.000000  1674.000000  1674.000000
mean    3003.211899   345.429290   704.001133   438.405094   229.404338
std     1348.592958   168.990249   140.511945   128.661168    58.349850
min     1028.493896   116.619843   357.657898   130.626099   121.525017
25%     1665.745483   198.522514   592.183105   348.079208   190.030106
50%     2915.264526   310.376785   708.663025   473.371170   214.961723
75%     4141.899414   387.118492   788.604065   543.495132   266.051239
max     6492.000488   902.284058   996.419800   640.888794   370.384399

In [8]:
returns = data.pct_change(fill_method=None).dropna()
returns

Ticker      CRISIL.NS        GS  HDFCBANK.NS      MSCI         V
Date
2019-01-03   0.008000 -0.014649    -0.007846 -0.038111 -0.036037
2019-01-04  -0.007082  0.032682     0.002675  0.037215  0.043081
2019-01-07   0.008239  0.005541     0.001511  0.004638  0.018033
2019-01-08  -0.007196 -0.003693    -0.008323  0.020777  0.005439
2019-01-09   0.005928  0.006273     0.006562  0.009778  0.011769
...               ...       ...          ...       ...       ...
2025-12-24   0.004330  0.010059     0.000602  0.000774  0.004980
2025-12-26  -0.007434 -0.004106    -0.005114  0.005569 -0.000394
2025-12-29   0.010660 -0.016383    -0.000403  0.001316 -0.001099
2025-12-30  -0.026346 -0.008698    -0.000807 -0.005992 -0.002792
2025-12-31   0.031187 -0.006128     0.000303 -0.014633 -0.008229

[1673 rows x 5 columns]

In [9]:
returns.shape

(1673, 5)

In [10]:
cov_matrix = returns.cov()
cov_matrix

Ticker       CRISIL.NS        GS  HDFCBANK.NS      MSCI         V
Ticker
CRISIL.NS     0.000452  0.000034     0.000056  0.000037  0.000027
GS            0.000034  0.000418     0.000070  0.000205  0.000193
HDFCBANK.NS   0.000056  0.000070     0.000257  0.000047  0.000060
MSCI          0.000037  0.000205     0.000047  0.000463  0.000204
V             0.000027  0.000193     0.000060  0.000204  0.000272

In [11]:
corr_matrix = returns.corr()
corr_matrix

Ticker       CRISIL.NS        GS  HDFCBANK.NS      MSCI         V
Ticker
CRISIL.NS     1.000000  0.077564     0.165053  0.080848  0.078261
GS            0.077564  1.000000     0.213198  0.466452  0.574016
HDFCBANK.NS   0.165053  0.213198     1.000000  0.135153  0.226517
MSCI          0.080848  0.466452     0.135153  1.000000  0.575411
V             0.078261  0.574016     0.226517  0.575411  1.000000

In [12]:
mean_returns = returns.mean()
mean_returns

Ticker
CRISIL.NS      0.000875
GS             0.001281
HDFCBANK.NS    0.000538
MSCI           0.001089
V              0.000745
dtype: float64

In [13]:
weights = np.array([0.2,0.2,0.2,0.2,0.2])

In [14]:
portfolio_returns = weights @ mean_returns
print(f"The portfolio return is: {round(portfolio_returns,4)}")
portfolio_returns.shape

The portfolio return is: 0.0009

()

In [15]:
portfolio_variance = np.dot(weights.T, np.dot(cov_matrix, weights))
print(f"The portfolio variance is: {round(portfolio_variance,4)}")

The portfolio variance is: 0.0001

In [16]:
portoflio_standard_deviation = np.sqrt(portfolio_variance)
print(f"The portfolio standard deviation is: {round(portoflio_standard_deviation,4)}")

The portfolio standard deviation is: 0.0122

**IMPLEMENTING SCIPY TO MINIMISE THE WEIGHTS**

In [17]:
from scipy.optimize import minimize

In [18]:
def calculate_portfolio_variance(weights,cov_matrix):
  return np.dot(weights.T, np.dot(cov_matrix, weights))

In [19]:
num_assets = 5
constraints = ({"type":"eq" , "fun": lambda w:np.sum(w) - 1})
bounds = tuple((0,1) for _ in range(num_assets))
initial_guess = num_assets * [1./num_assets]

In [20]:
results = minimize(calculate_portfolio_variance, initial_guess, args=(cov_matrix,), method='SLSQP', bounds=bounds, constraints=constraints,tol=1e-12)

In [21]:
min_var_weights = results.x
print(f"The minimum variance portfolio weights are: {min_var_weights}")

The minimum variance portfolio weights are: [0.21558415 0.07116928 0.36592455 0.07790989 0.26941213]

In [22]:
portfolio_returns = returns @ min_var_weights
print(f"The minimum variance portfolio returns are: {portfolio_returns}")

The minimum variance portfolio returns are: Date
2019-01-03   -0.014867
2019-01-04    0.016284
2019-01-07    0.007943
2019-01-08   -0.001776
2019-01-09    0.008058
                ...
2025-12-24    0.003272
2025-12-26   -0.003439
2025-12-29    0.000791
2025-12-30   -0.007813
2025-12-31    0.003041
Length: 1673, dtype: float64

In [23]:
portfolio_returns.shape

(1673,)

**FEATURE ENGINEERING**

In [24]:
df = pd.DataFrame(index=portfolio_returns.index)
df['lagged_return'] = portfolio_returns.shift(1)
df['rolling_avg_10'] = portfolio_returns.rolling(10).mean().shift(1)
print(df.head())

            lagged_return  rolling_avg_10
Date
2019-01-03            NaN             NaN
2019-01-04      -0.014867             NaN
2019-01-07       0.016284             NaN
2019-01-08       0.007943             NaN
2019-01-09      -0.001776             NaN

In [25]:
tickers = ['GS','MSCI','V','CRISIL.NS','HDFCBANK.NS']
volume_data = yf.download(tickers=tickers,start='2019-01-01',end='2026-01-01')['Volume']

/tmp/ipykernel_924/1056902159.py:2: FutureWarning: YF.download() has changed argument auto_adjust default to True
  volume_data = yf.download(tickers=tickers,start='2019-01-01',end='2026-01-01')['Volume']
[*********************100%***********************]  5 of 5 completed

In [26]:
print(volume_data.head())

Ticker      CRISIL.NS         GS  HDFCBANK.NS      MSCI           V
Date
2019-01-01     1390.0        NaN    6373440.0       NaN         NaN
2019-01-02    10263.0  3999400.0    8134232.0  637500.0   8788000.0
2019-01-03     5612.0  4060200.0   12771664.0  852100.0   9428300.0
2019-01-04     1522.0  3788300.0    7287120.0  599900.0  11065800.0
2019-01-07     6337.0  3152100.0    5387012.0  795300.0  12928000.0

In [27]:
volume_data.isnull().sum().sum()

np.int64(340)

In [28]:
volume_data.dropna(inplace=True)

In [29]:
volume_data.isnull().sum().sum()

np.int64(0)

In [30]:
df['rolling_vol_10'] = portfolio_returns.rolling(10).std().shift(1)
print(df.head())

            lagged_return  rolling_avg_10  rolling_vol_10
Date
2019-01-03            NaN             NaN             NaN
2019-01-04      -0.014867             NaN             NaN
2019-01-07       0.016284             NaN             NaN
2019-01-08       0.007943             NaN             NaN
2019-01-09      -0.001776             NaN             NaN

In [31]:
ff_daily = web.DataReader('F-F_Research_Data_Factors_daily', 'famafrench', start='2019-01-01', end='2026-01-01')[0] / 100
print(ff_daily.head())

            Mkt-RF     SMB     HML      RF
Date
2019-01-02  0.0022  0.0058  0.0114  0.0001
2019-01-03 -0.0245  0.0036  0.0118  0.0001
2019-01-04  0.0355  0.0040 -0.0069  0.0001
2019-01-07  0.0094  0.0101 -0.0075  0.0001
2019-01-08  0.0101  0.0052 -0.0063  0.0001

In [32]:
def rolling_beta(window_returns, market_returns):
    if len(window_returns) < 2:
        return np.nan
    covariance = np.cov(window_returns, market_returns.loc[window_returns.index])[0,1]
    market_variance = np.var(market_returns.loc[window_returns.index])
    return covariance / market_variance

In [33]:
window = 60
rolling_betas = []

for i in range(len(portfolio_returns)):
    if i < window:
        rolling_betas.append(np.nan)
    else:
        window_returns = portfolio_returns.iloc[i-window:i]
        market_window = ff_daily['Mkt-RF'].reindex(window_returns.index)
        cov = np.cov(window_returns, market_window)[0,1]
        var = np.var(market_window)
        rolling_betas.append(cov/var)

df['rolling_beta_60'] = rolling_betas

In [34]:
ff_daily.index = ff_daily.index.to_timestamp()
print(ff_daily.index[:3])
print(ff_daily.index.dtype)

DatetimeIndex(['2019-01-02', '2019-01-03', '2019-01-04'], dtype='datetime64[ns]', name='Date', freq=None)
datetime64[ns]

In [35]:
rolling_cov = portfolio_returns.rolling(60).cov(ff_daily['Mkt-RF'])
rolling_market_var = ff_daily['Mkt-RF'].rolling(60).var()

df['rolling_beta_60'] = (rolling_cov / rolling_market_var).shift(1)

In [36]:
print(df['rolling_beta_60'].dropna().head())
print(df['rolling_beta_60'].isna().sum())

Date
2020-02-11    0.713368
2020-02-12    0.704722
2020-02-13    0.712253
2020-02-14    0.701824
2020-02-18    0.701173
Name: rolling_beta_60, dtype: float64
1599

In [37]:
df['rolling_var_60'] = portfolio_returns.rolling(60).quantile(0.05).shift(1)
print(df.head())

            lagged_return  rolling_avg_10  rolling_vol_10  rolling_beta_60  \
Date
2019-01-03            NaN             NaN             NaN              NaN
2019-01-04      -0.014867             NaN             NaN              NaN
2019-01-07       0.016284             NaN             NaN              NaN
2019-01-08       0.007943             NaN             NaN              NaN
2019-01-09      -0.001776             NaN             NaN              NaN

            rolling_var_60
Date
2019-01-03             NaN
2019-01-04             NaN
2019-01-07             NaN
2019-01-08             NaN
2019-01-09             NaN

In [38]:
df['target'] = (portfolio_returns.shift(-1) > 0).astype(int)
print(df.tail())

            lagged_return  rolling_avg_10  rolling_vol_10  rolling_beta_60  \
Date
2025-12-24       0.002644        0.002393        0.009448              NaN
2025-12-26       0.003272        0.003148        0.009153              NaN
2025-12-29      -0.003439        0.000285        0.005051              NaN
2025-12-30       0.000791       -0.000255        0.004619              NaN
2025-12-31      -0.007813       -0.000635        0.005094              NaN

            rolling_var_60  target
Date
2025-12-24       -0.008443       0
2025-12-26       -0.008443       1
2025-12-29       -0.008443       0
2025-12-30       -0.008443       1
2025-12-31       -0.008443       0

In [39]:
target_return = portfolio_returns.shift(-1)
df['target'] = np.where(target_return.isna(), np.nan, (target_return > 0).astype(int))

In [40]:
print(ff_daily.index.min(), ff_daily.index.max())
print(portfolio_returns.index.min(), portfolio_returns.index.max())

2019-01-02 00:00:00 2025-12-31 00:00:00
2019-01-03 00:00:00 2025-12-31 00:00:00

In [41]:
rolling_cov = portfolio_returns.rolling(60).cov(ff_daily['Mkt-RF'])
rolling_market_var = ff_daily['Mkt-RF'].rolling(60).var()
df['rolling_beta_60'] = (rolling_cov / rolling_market_var).shift(1)

print(df['rolling_beta_60'].isna().sum())
print(df['rolling_beta_60'].notna().sum())

1599
74

In [42]:
common_dates = portfolio_returns.index.intersection(ff_daily.index)
print(len(common_dates))
print(len(portfolio_returns))
print(len(ff_daily))

1673
1673
1760

In [43]:
ff_daily_aligned = ff_daily.loc[portfolio_returns.index]
print(ff_daily_aligned.shape)

rolling_cov = portfolio_returns.rolling(60).cov(ff_daily_aligned['Mkt-RF'])
rolling_market_var = ff_daily_aligned['Mkt-RF'].rolling(60).var()
df['rolling_beta_60'] = (rolling_cov / rolling_market_var).shift(1)

print(df['rolling_beta_60'].isna().sum())
print(df['rolling_beta_60'].notna().sum())

(1673, 4)
60
1613

In [44]:
df_clean = df.dropna()
print(df_clean.shape)
print(df_clean.head())

(1612, 6)
            lagged_return  rolling_avg_10  rolling_vol_10  rolling_beta_60  \
Date
2019-04-05      -0.000257        0.000931        0.006178         0.511984
2019-04-08       0.005768        0.001443        0.006361         0.495077
2019-04-09       0.001265        0.002189        0.005776         0.516395
2019-04-10      -0.004257        0.001856        0.006065         0.513954
2019-04-11       0.001634        0.000875        0.005050         0.534467

            rolling_var_60  target
Date
2019-04-05       -0.008425     1.0
2019-04-08       -0.008303     0.0
2019-04-09       -0.008303     1.0
2019-04-10       -0.008303     1.0
2019-04-11       -0.008303     1.0

**TRAIN/TEST SPLITTING**

In [45]:
x = df_clean.drop('target', axis=1)
y = df_clean['target']

In [46]:
from sklearn.model_selection import train_test_split

In [47]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [48]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(1289, 5)
(1289,)
(323, 5)
(323,)

**IMPLEMENTING AN XGBOOST CLASSIFIER ON THE DATA**

In [49]:
from xgboost import XGBClassifier
from sklearn import metrics
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [50]:
model = XGBClassifier(n_estimators=200, max_depth=3, learning_rate=0.1, random_state=42)

In [51]:
model.fit(x_train,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.1, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=3,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=200,
              n_jobs=None, num_parallel_tree=None, ...)

In [52]:
y_pred = model.predict(x_test)

In [53]:
accuracy = accuracy_score(y_test, y_pred)
print(f"Test Accuracy: {accuracy:.4f}")
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Test Accuracy: 0.5108

Classification Report:
               precision    recall  f1-score   support

         0.0       0.50      0.43      0.46       159
         1.0       0.52      0.59      0.55       164

    accuracy                           0.51       323
   macro avg       0.51      0.51      0.51       323
weighted avg       0.51      0.51      0.51       323

In [54]:
print(confusion_matrix(y_test, y_pred))

[[68 91]
 [67 97]]

**BACKTESTING STRATEGY**

In [55]:
y_pred

array([1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1])

In [56]:
prediction_matrix = pd.DataFrame({
    "y_pred": y_pred,
})

In [57]:
exposure= np.where(prediction_matrix["y_pred"] == 1, 1.0, 0.5)

In [58]:
test_dates = y_test.index
actual_returns_test = portfolio_returns.loc[test_dates]
print(actual_returns_test.shape)

(323,)

In [59]:
strategy_returns = exposure * actual_returns_test.values
buy_and_hold_returns = actual_returns_test.values

print(strategy_returns[:10])
print(buy_and_hold_returns[:10])

[-0.00099582 -0.01130413  0.0121022   0.00141503  0.0353085   0.01186977
 -0.00074985 -0.00353734 -0.0197506   0.02404518]
[-0.00099582 -0.02260826  0.0121022   0.00283007  0.0353085   0.01186977
 -0.0014997  -0.00707469 -0.0197506   0.02404518]

In [63]:
strategy_cumulative_return = (1 + strategy_returns).cumprod() - 1
buy_and_hold_cumulative_return = (1 + buy_and_hold_returns).cumprod() - 1
print(strategy_cumulative_return)
print(buy_and_hold_cumulative_return)

[-9.95818631e-04 -1.22886907e-02 -3.35211383e-04  1.07934908e-03
  3.64259610e-02  4.87281012e-02  4.79417108e-02  4.42347809e-02
  2.36105224e-02  4.82234172e-02  4.30118867e-02  3.80758605e-02
  3.25133611e-02  5.13687819e-02  5.21032287e-02  4.79379321e-02
  5.00203759e-02  5.73791977e-02  6.07348432e-02  5.41302740e-02
  4.77190462e-02  4.60614705e-02  4.96461301e-02  5.00806648e-02
  5.82664167e-02  5.83109745e-02  6.37363758e-02  6.41610584e-02
  6.63478016e-02  6.78203072e-02  6.16580151e-02  5.69107334e-02
  5.64561042e-02  3.68059093e-02  3.47708961e-02  4.04546526e-02
  4.35291797e-02  4.27105871e-02  4.11284423e-02  3.99760361e-02
  4.08660969e-02  4.37188565e-02  3.65310827e-02  4.24721738e-02
  4.71688218e-02  5.29622850e-02  7.29440495e-02  8.18549331e-02
  8.08102543e-02  7.73715000e-02  7.43776226e-02  7.85284029e-02
  8.97218945e-02  9.34295931e-02  9.20585027e-02  8.90168038e-02
  8.87862433e-02  9.29618908e-02  8.30591161e-02  8.23544149e-02
  8.48134260e-02  8.36380278e-02  7.22522802e-02  6.53549771e-02
  6.57717178e-02  6.24065048e-02  5.56688656e-02  6.09616928e-02
  6.70332091e-02  6.57543744e-02  7.14207092e-02  7.48157950e-02
  7.61173297e-02  7.65280948e-02  7.93946016e-02  6.87642140e-02
  6.63154357e-02  6.55258872e-02  5.74351384e-02  6.56055856e-02
  6.60387950e-02  1.13715151e-01  1.01950281e-01  1.10695168e-01
  1.09928339e-01  1.03626492e-01  1.20762656e-01  1.28211761e-01
  1.32374672e-01  1.33389641e-01  1.28392745e-01  1.33321931e-01
  1.34171295e-01  1.39575304e-01  1.66937650e-01  1.86731226e-01
  1.94196237e-01  1.89374845e-01  1.63562986e-01  1.57603171e-01
  1.58364219e-01  1.53961179e-01  1.82003883e-01  1.74940273e-01
  1.72565867e-01  1.62124768e-01  1.67448232e-01  1.63888370e-01
  1.82324954e-01  1.80814273e-01  1.76600139e-01  1.75831404e-01
  1.95795892e-01  1.96184770e-01  1.86811581e-01  1.82421218e-01
  1.74936143e-01  1.81269518e-01  1.77065978e-01  1.81242786e-01
  1.96300917e-01  1.92492499e-01  1.90255321e-01  1.96099532e-01
  1.93716068e-01  1.99434519e-01  2.05679781e-01  2.03917989e-01
  2.01304626e-01  2.04156611e-01  2.14826809e-01  2.16920465e-01
  2.11622923e-01  2.17649310e-01  2.17015305e-01  2.27570152e-01
  2.05862023e-01  2.22649328e-01  2.32787207e-01  2.33468310e-01
  2.57878775e-01  2.54602387e-01  2.22042699e-01  2.11848939e-01
  2.13294009e-01  2.07574114e-01  2.07317087e-01  2.01800295e-01
  2.11972499e-01  2.22496366e-01  2.31804088e-01  2.18401541e-01
  2.17926722e-01  2.07578227e-01  2.07301478e-01  2.11454263e-01
  2.12394345e-01  2.16756337e-01  2.04445225e-01  2.03342511e-01
  2.01607089e-01  1.98751819e-01  2.05468626e-01  2.46501798e-01
  2.60193442e-01  2.82407943e-01  2.78907213e-01  2.79460775e-01
  2.68671954e-01  2.67104609e-01  2.64244645e-01  2.60041073e-01
  2.43019320e-01  2.47473446e-01  2.54198805e-01  2.59913187e-01
  2.64276642e-01  2.64492148e-01  3.15855076e-01  3.24453098e-01
  3.23626066e-01  3.29826145e-01  3.38968204e-01  3.42904541e-01
  3.45948779e-01  3.34993020e-01  3.24961774e-01  3.30641717e-01
  3.26335696e-01  3.31783134e-01  3.24314662e-01  3.35859941e-01
  3.15935781e-01  3.26227111e-01  3.29734253e-01  3.26286698e-01
  3.22104994e-01  3.37789502e-01  3.33777923e-01  3.37854766e-01
  3.41391193e-01  3.14875280e-01  3.19630221e-01  3.19765195e-01
  3.00714492e-01  2.95490984e-01  3.07530867e-01  2.99163334e-01
  3.04323732e-01  3.19501900e-01  3.21828425e-01  3.31723572e-01
  3.22979645e-01  3.31517934e-01  3.39131843e-01  3.46955998e-01
  3.32812728e-01  3.26011413e-01  3.22378377e-01  3.28439657e-01
  3.09169471e-01  2.98747927e-01  2.94790348e-01  2.95089872e-01
  2.96379991e-01  2.95465119e-01  2.97390526e-01  3.01441902e-01
  3.03827174e-01  2.96929830e-01  2.93339812e-01  2.67730717e-01
  2.67377804e-01  2.59675321e-01  2.51880450e-01  2.62877654e-01
  2.59736514e-01  2.65472903e-01  2.64199857e-01  2.69950535e-01
  2.86755794e-01  2.90570699e-01  2.87448651e-01  2.92234846e-01
  2.81038887e-01  2.86125202e-01  2.92289151e-01  2.98066241e-01
  3.02108935e-01  3.09845133e-01  3.10715135e-01  3.11883880e-01
  3.17298547e-01  3.14711824e-01  3.16538818e-01  3.11380361e-01
  3.13371029e-01  3.23077172e-01  3.14197650e-01  3.25070745e-01
  3.24724323e-01  3.21990052e-01  3.14450563e-01  3.11434044e-01
  3.01095139e-01  3.01386644e-01  3.05961713e-01  3.04251576e-01
  3.12904166e-01  3.04368102e-01  3.01594619e-01  3.08884040e-01
  2.98442781e-01  3.26353633e-01  3.36540799e-01  3.27905958e-01
  3.32039354e-01  3.14279307e-01  3.18039838e-01  3.24624249e-01
  3.36547581e-01  3.37542844e-01  3.52705906e-01  3.62682297e-01
  3.63683282e-01  3.63116583e-01  3.73357428e-01  3.85183931e-01
  3.82813611e-01  3.81489705e-01  3.86794252e-01  4.88337300e-01
  4.86324103e-01  4.66794592e-01  4.74423667e-01  4.73083569e-01
  4.84724635e-01  4.77364942e-01  4.89564202e-01  4.87508531e-01
  4.90340985e-01  4.85549572e-01  4.90319211e-01  4.92774862e-01
  5.00880839e-01  5.01145635e-01  5.06799089e-01  4.82606727e-01
  4.80379964e-01  5.14847969e-01  5.12090977e-01  4.93411985e-01
  4.95198960e-01  4.92738640e-01  4.85551660e-01  4.58387216e-01
  4.49383051e-01  4.61868696e-01  4.61098771e-01  4.57414969e-01
  4.65898882e-01  4.76320383e-01  4.72402034e-01]
[-0.00099582 -0.02358156 -0.01176475 -0.00896798  0.02602388  0.03820255
  0.03664555  0.02931161  0.00898209  0.03324324  0.02296914  0.01812796
  0.00721675  0.02561021  0.02704311  0.02297703  0.02500987  0.03219342
  0.03546913  0.02902188  0.01650484  0.01489665  0.01837451  0.0187961
  0.02673798  0.02678121  0.03730874  0.03772287  0.0419877   0.04486544
  0.03883561  0.03419038  0.03330067  0.01408117  0.01209076  0.01764994
  0.02366422  0.02286121  0.01975716  0.01749966  0.01837048  0.02395269
  0.00984939  0.02142571  0.02602753  0.03170403  0.05128239  0.06001337
  0.05796619  0.05123405  0.0483128   0.05236288  0.06328482  0.07052031
  0.06783559  0.06188712  0.06143749  0.06550825  0.04620019  0.04483875
  0.04721253  0.04494322  0.03396403  0.02731302  0.02811674  0.02162411
  0.0086661   0.01372327  0.01952446  0.01708067  0.02248822  0.02572825
  0.02821243  0.02899739  0.03447728  0.02428926  0.02194238  0.020429
  0.00493236  0.01269714  0.01310884  0.10372719  0.09206783  0.10073429
  0.09997433  0.093729    0.11071149  0.11809379  0.12634494  0.12735451
  0.12238422  0.1321901   0.13303861  0.14383584  0.17130048  0.19116806
  0.19866098  0.19382156  0.1679132   0.1619311   0.16345889  0.15461408
  0.18267265  0.16853744  0.16617597  0.14540757  0.15065446  0.14363715
  0.16175294  0.15878415  0.15464864  0.15389425  0.17348626  0.17424951
  0.1558469   0.14729526  0.13276983  0.14498199  0.14090758  0.14495608
  0.1741472   0.16667142  0.16229394  0.17370778  0.1690301   0.17463029
  0.1807464   0.17902104  0.1739024   0.17668933  0.18711614  0.18916204
  0.17880863  0.19053498  0.18991509  0.20023491  0.17901017  0.19542366
  0.20533579  0.20666766  0.23054774  0.22413734  0.19236829  0.18242206
  0.18524202  0.17965437  0.17940329  0.17401405  0.18395107  0.19423162
  0.20332414  0.19023147  0.18976762  0.16954916  0.16928113  0.17330313
  0.17421361  0.18266286  0.15873055  0.15660882  0.15327278  0.15053236
  0.15697898  0.19636161  0.20950251  0.23082344  0.22410361  0.22516329
  0.20450136  0.20301329  0.19758268  0.19360076  0.17747654  0.18169581
  0.18806655  0.19889269  0.20304481  0.20345495  0.25233858  0.26052157
  0.25894735  0.26484446  0.28223513  0.28977423  0.29269803  0.27165341
  0.26209811  0.27291902  0.26468056  0.26987477  0.26275348  0.28477066
  0.26560849  0.27550623  0.27887925  0.27224784  0.26823651  0.28328197
  0.27943384  0.28334457  0.28673691  0.26130137  0.27042378  0.27068366
  0.23399923  0.22904364  0.24046598  0.23252763  0.23742335  0.26622267
  0.26845525  0.28744645  0.27899324  0.28724765  0.29460841  0.30973645
  0.29598399  0.28275723  0.27572818  0.28742308  0.26874788  0.24854834
  0.24474373  0.24503167  0.24751218  0.24575141  0.24945445  0.25335613
  0.25795042  0.24464111  0.23775055  0.18873378  0.18807194  0.18085144
  0.16623722  0.17648208  0.17062959  0.18129084  0.17891412  0.18963957
  0.22112458  0.22836523  0.2224221   0.23151101  0.21017131  0.21978119
  0.22562717  0.23110626  0.23494041  0.24227754  0.24392779  0.24503698
  0.25017574  0.24526591  0.2469964   0.24211042  0.24588145  0.25508883
  0.2466656   0.25697996  0.25632272  0.25113655  0.24400114  0.23829145
  0.22852918  0.22907967  0.23772142  0.23447986  0.25085929  0.23459395
  0.23196883  0.24576781  0.23583004  0.262395    0.27209092  0.26387247
  0.26780654  0.25090291  0.2580613   0.26434608  0.27572683  0.2766768
  0.29114986  0.30067226  0.3016277   0.30108679  0.32063644  0.33200894
  0.32745029  0.32490848  0.32999577  0.42737996  0.42351847  0.40481419
  0.4121209   0.40955395  0.42069298  0.41365068  0.42532383  0.42335681
  0.42877741  0.42418392  0.42875653  0.43346496  0.44124887  0.44150315
  0.45236082  0.42904249  0.42689617  0.46011891  0.45480413  0.41886149
  0.42055926  0.41822176  0.41139355  0.38558514  0.37703046  0.38889283
  0.38742985  0.38043372  0.38846951  0.39834054  0.39462916]

In [61]:
strategy_sharpe_ratio = (strategy_returns.mean() / strategy_returns.std()) * np.sqrt(252)
buy_and_hold_sharpe_ratio = (buy_and_hold_returns.mean() / buy_and_hold_returns.std()) * np.sqrt(252)

In [62]:
cumulative_strat = pd.Series((1 + strategy_returns).cumprod())
cumulative_bh = pd.Series((1 + buy_and_hold_returns).cumprod())

max_drawdown_strat = (cumulative_strat / cumulative_strat.cummax() - 1).min()
max_drawdown_bh = (cumulative_bh / cumulative_bh.cummax() - 1).min()

print(max_drawdown_strat, max_drawdown_bh)

-0.07058548926281538 -0.10956343860026363