In [13]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import yfinance as yf

**DOWNLOADING DATA FROM YFINANCE**

In [14]:
tickers = ['GS','MSCI','V','CRISIL.NS','HDFCBANK.NS']
data = yf.download(tickers=tickers,start='2019-01-01',end='2026-01-01')['Close']
data

/tmp/ipykernel_1411/2009219871.py:2: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(tickers=tickers,start='2019-01-01',end='2026-01-01')['Close']
[*********************100%***********************]  5 of 5 completed

Ticker        CRISIL.NS          GS  HDFCBANK.NS        MSCI           V
Date
2019-01-01  1430.623901         NaN   496.185883         NaN         NaN
2019-01-02  1435.571655  144.753723   491.658478  135.801590  126.068077
2019-01-03  1447.056030  142.633255   487.801025  130.626129  121.525009
2019-01-04  1436.808472  147.294876   489.106079  135.487366  126.760452
2019-01-07  1448.646240  148.111069   489.845215  136.115829  129.046219
...                 ...         ...          ...         ...         ...
2025-12-24  4240.708496  902.036438   980.975220  577.381104  353.675964
2025-12-26  4209.180664  898.332336   975.958191  580.596802  353.536560
2025-12-29  4254.050781  883.614990   975.564697  581.361023  353.148132
2025-12-30  4141.974609  875.929443   974.777771  577.877380  352.162231
2025-12-31  4271.149414  870.561523   975.072876  569.421326  349.264221

[1816 rows x 5 columns]

**EXPLORATORY DATA ANALYSIS**

In [15]:
data.isnull().sum().sum()

np.int64(340)

In [18]:
data.dropna(inplace=True)

In [19]:
data.isnull().sum().sum()

np.int64(0)

In [20]:
data.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 1674 entries, 2019-01-02 to 2025-12-31
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   CRISIL.NS    1674 non-null   float64
 1   GS           1674 non-null   float64
 2   HDFCBANK.NS  1674 non-null   float64
 3   MSCI         1674 non-null   float64
 4   V            1674 non-null   float64
dtypes: float64(5)
memory usage: 78.5 KB

In [21]:
data.describe()

Ticker    CRISIL.NS           GS  HDFCBANK.NS         MSCI            V
count   1674.000000  1674.000000  1674.000000  1674.000000  1674.000000
mean    3003.211905   345.429292   704.001135   438.405093   229.404338
std     1348.592966   168.990251   140.511944   128.661169    58.349849
min     1028.493530   116.619789   357.657928   130.626129   121.525009
25%     1665.745392   198.522572   592.183105   348.079254   190.030121
50%     2915.264282   310.376770   708.663025   473.371170   214.961708
75%     4141.899292   387.118454   788.604050   543.495132   266.051239
max     6492.000977   902.284058   996.419800   640.888794   370.384399

In [25]:
returns = data.pct_change(fill_method=None).dropna()
returns

Ticker      CRISIL.NS        GS  HDFCBANK.NS      MSCI         V
Date
2019-01-03   0.008000 -0.014649    -0.007846 -0.038110 -0.036037
2019-01-04  -0.007082  0.032683     0.002675  0.037215  0.043081
2019-01-07   0.008239  0.005541     0.001511  0.004639  0.018032
2019-01-08  -0.007196 -0.003693    -0.008323  0.020777  0.005439
2019-01-09   0.005927  0.006273     0.006562  0.009778  0.011769
...               ...       ...          ...       ...       ...
2025-12-24   0.004330  0.010059     0.000602  0.000774  0.004980
2025-12-26  -0.007435 -0.004106    -0.005114  0.005569 -0.000394
2025-12-29   0.010660 -0.016383    -0.000403  0.001316 -0.001099
2025-12-30  -0.026346 -0.008698    -0.000807 -0.005992 -0.002792
2025-12-31   0.031187 -0.006128     0.000303 -0.014633 -0.008229

[1673 rows x 5 columns]

In [26]:
returns.shape

(1673, 5)

In [28]:
cov_matrix = returns.cov()
cov_matrix

Ticker       CRISIL.NS        GS  HDFCBANK.NS      MSCI         V
Ticker
CRISIL.NS     0.000452  0.000034     0.000056  0.000037  0.000027
GS            0.000034  0.000418     0.000070  0.000205  0.000193
HDFCBANK.NS   0.000056  0.000070     0.000257  0.000047  0.000060
MSCI          0.000037  0.000205     0.000047  0.000463  0.000204
V             0.000027  0.000193     0.000060  0.000204  0.000272

In [29]:
corr_matrix = returns.corr()
corr_matrix

Ticker       CRISIL.NS        GS  HDFCBANK.NS      MSCI         V
Ticker
CRISIL.NS     1.000000  0.077564     0.165054  0.080848  0.078261
GS            0.077564  1.000000     0.213199  0.466452  0.574016
HDFCBANK.NS   0.165054  0.213199     1.000000  0.135153  0.226517
MSCI          0.080848  0.466452     0.135153  1.000000  0.575412
V             0.078261  0.574016     0.226517  0.575412  1.000000

In [31]:
mean_returns = returns.mean()
mean_returns

Ticker
CRISIL.NS      0.000875
GS             0.001281
HDFCBANK.NS    0.000538
MSCI           0.001089
V              0.000745
dtype: float64

In [32]:
weights = np.array([0.2,0.2,0.2,0.2,0.2])

In [33]:
portfolio_returns = weights @ mean_returns
print(f"The portfolio return is: {round(portfolio_returns,4)}")
portfolio_returns.shape

The portfolio return is: 0.0009

()

In [34]:
portfolio_variance = np.dot(weights.T, np.dot(cov_matrix, weights))
print(f"The portfolio variance is: {round(portfolio_variance,4)}")

The portfolio variance is: 0.0001

In [35]:
portoflio_standard_deviation = np.sqrt(portfolio_variance)
print(f"The portfolio standard deviation is: {round(portoflio_standard_deviation,4)}")

The portfolio standard deviation is: 0.0122

**IMPLEMENTING SCIPY TO MINIMISE THE WEIGHTS**