**TESTING MODERN PORTFOLIO THEORY ON GOLDMAN SACHS, CRISIL, HDFC BANK, MORGAN STANLEY CAPITAL INDEX, VISA**

In [1]:
import yfinance as yf
import pandas as pd
import numpy as np

In [2]:
tickers = ['GS', 'MSCI', 'V', 'CRISIL.NS', 'HDFCBANK.NS']
data = yf.download(tickers, start='2019-01-01', end='2026-01-01')['Close']
print(data.shape)
print(data.head())

/tmp/ipykernel_661/785333385.py:2: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(tickers, start='2019-01-01', end='2026-01-01')['Close']
[*********************100%***********************]  5 of 5 completed

(1816, 5)
Ticker        CRISIL.NS          GS  HDFCBANK.NS        MSCI           V
Date
2019-01-01  1433.922607         NaN   496.185883         NaN         NaN
2019-01-02  1438.881714  144.753708   491.658478  135.801575  126.068100
2019-01-03  1450.392334  142.633255   487.800995  130.626129  121.525047
2019-01-04  1440.121094  147.294861   489.106049  135.487427  126.760437
2019-01-07  1451.985840  148.111084   489.845245  136.115814  129.046219

In [3]:
print(data.isna().sum())
print(data.isna().sum().sum())

Ticker
CRISIL.NS      86
GS             56
HDFCBANK.NS    86
MSCI           56
V              56
dtype: int64
340

In [4]:
data_clean = data.dropna()
print(data_clean.shape)
print(data_clean.isna().sum().sum())

(1674, 5)
0

In [7]:
returns = data_clean.pct_change(fill_method=None).dropna()
returns.shape

(1673, 5)

In [12]:
cov_matrix = returns.cov()
cov_matrix

Ticker       CRISIL.NS        GS  HDFCBANK.NS      MSCI         V
Ticker
CRISIL.NS     0.000452  0.000034     0.000056  0.000037  0.000027
GS            0.000034  0.000418     0.000070  0.000205  0.000193
HDFCBANK.NS   0.000056  0.000070     0.000257  0.000047  0.000060
MSCI          0.000037  0.000205     0.000047  0.000463  0.000204
V             0.000027  0.000193     0.000060  0.000204  0.000272

In [13]:
corr_matrix = returns.corr()
corr_matrix

Ticker       CRISIL.NS        GS  HDFCBANK.NS      MSCI         V
Ticker
CRISIL.NS     1.000000  0.077564     0.165054  0.080848  0.078261
GS            0.077564  1.000000     0.213199  0.466452  0.574016
HDFCBANK.NS   0.165054  0.213199     1.000000  0.135153  0.226517
MSCI          0.080848  0.466452     0.135153  1.000000  0.575411
V             0.078261  0.574016     0.226517  0.575411  1.000000